### ISSUE TITLE
Where to find more info on errors?

### ISSUE THREAD

**Issue by thereddestdog** [benfoxall/lastfm-to-csv#28]
Where can I find more information on these errors I sometimes see?

![image](https://github.com/benfoxall/lastfm-to-csv/assets/24947579/356513b4-98cd-43bf-9661-93f7cda0a817)

**Comment by benfoxall** [comment]
Hey @thereddestdog,

I've just made a change 5b143818ebed22ffe9b75f676719bd40b8f2d6e9 - so now the errors will be printed to the browser console.

Let me know what errors you see, and I'll try and make a fix (usually it's to do with oddly-named bands)

**Comment by thereddestdog** [comment]
Hi Ben,

Not sure what these errors are

![image](https://github.com/benfoxall/lastfm-to-csv/assets/24947579/a90a3a1b-7ff5-4ca6-b757-5c050827175a)

**Comment by benfoxall** [comment]
Hey @thereddestdog,

I managed to request those pages without hitting any errors:

![Screenshot 2024-05-22 at 08 13 37](https://github.com/benfoxall/lastfm-to-csv/assets/51385/7fb02da6-c416-4867-bd23-f40feabb812e)

Though I did get a few later on:
![image](https://github.com/benfoxall/lastfm-to-csv/assets/51385/b7af86d2-106a-431b-bca3-3bfd065cf4a0)

…I managed to re-run one of those requests, I saw [the same error](https://www.last.fm/api/errorcodes#:~:text=8%20%3A%20Operation%20failed%20%2D%20Most%20likely%20the%20backend%20service%20failed.%20Please%20try%20again.) at first but then after a few seconds it cleared.

So it looks like it's a temporary service outage on the lastfm side 😢 (though respect where it's due, that last.fm api has been running and supporting the same requests for >10 years; they're doing a great job ❤️ ).

In terms of fixes, it would be possible to make some re-requests (maybe with some backoff logic) in the code.  

As a workaround, because the requests fail at different points in history you could download your csv a couple of times and then deduplicate by date.
